#!/usr/bin/env bash
# Optio-New secrets helper (sops + age). See docs/secrets.md.
# Never prints secret values. Do not enable shell xtrace.
set -euo pipefail
umask 077

ROOT="${OPTIO_NEW_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$ROOT"

PLAIN="${OPTIO_NEW_ENV_FILE:-$ROOT/.env}"
ENCRYPTED="${OPTIO_NEW_ENCRYPTED_ENV:-$ROOT/secrets/optio-new.env}"
SOPS_AGE_KEY_FILE="${SOPS_AGE_KEY_FILE:-$ROOT/secrets/age/key.txt}"
OPTIO_NEW_SOPS_CONFIG="${OPTIO_NEW_SOPS_CONFIG:-$ROOT/secrets/.sops.yaml}"
export SOPS_AGE_KEY_FILE

PLACEHOLDER_RECIPIENT="AGE_RECIPIENT_REPLACE_ME"
cleanup_paths=()

die() {
  echo "[secrets] FAIL: $*" >&2
  exit 1
}

add_cleanup() {
  cleanup_paths+=("$1")
}

cleanup() {
  local code=$?
  local path
  if [[ ${#cleanup_paths[@]} -gt 0 ]]; then
    for path in "${cleanup_paths[@]}"; do
      rm -rf "$path"
    done
  fi
  exit "$code"
}

trap cleanup EXIT

first_line() {
  local value="$1"
  printf '%s' "${value%%$'\n'*}"
}

usage() {
  cat <<'EOF'
Usage: scripts/secrets.sh <command>

  init            Create a host age key and secrets/.sops.yaml (public recipient only)
  encrypt [--force] [plaintext] [ciphertext]
                  Encrypt the host .env (default: .env -> secrets/optio-new.env)
  check           Decrypt and compare assignment hashes to the plaintext .env
  compose [args]  Decrypt to a tmpfs file and run docker compose --env-file
                  Boot set is COMPOSE_PROFILES=harness,orchestrator,edge
                  (deploy/systemd/optio-new-compose.service). Not a secret.
                  LiteLLM stays in the default service set.
  run <command>   Decrypt to a tmpfs file, export it, and run a command
  audit           Gitignore / tracked-file checks. Prints paths and rule ids only
  roundtrip       Encrypt and decrypt a placeholder env with a throwaway key

Host layout (kit-harness): /opt/optio-new
See docs/secrets.md. Production plaintext and ciphertext stay off git.
EOF
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing command: $1"
}

secret_tmp() {
  local dir="/dev/shm"
  if [[ ! -d "$dir" || ! -w "$dir" ]]; then
    dir="${TMPDIR:-/tmp}"
  fi
  mktemp "$dir/optio-new.env.XXXXXX"
}

read_recipient() {
  local file="$OPTIO_NEW_SOPS_CONFIG"
  [[ -f "$file" ]] || die "missing ${file}. Run: scripts/secrets.sh init"
  local recipient
  recipient="$(first_line "$(sed -n 's/^[[:space:]]*age:[[:space:]]*//p' "$file" | tr -d "\"'")")"
  [[ -n "$recipient" ]] || die "no age recipient in ${file}"
  if [[ "$recipient" == "$PLACEHOLDER_RECIPIENT" ]]; then
    die "recipient is still the example placeholder. Run: scripts/secrets.sh init"
  fi
  [[ "$recipient" == age1* ]] || die "age recipient in ${file} is not an age public key"
  printf '%s' "$recipient"
}

write_sops_config() {
  local recipient="$1"
  local file="$OPTIO_NEW_SOPS_CONFIG"
  mkdir -p "$(dirname "$file")"
  cat >"$file" <<EOF
# Generated by scripts/secrets.sh init. Gitignored.
# Public age recipient only. The private key stays on this host.
creation_rules:
  - path_regex: (^|/)optio-new\\.env$
    age: ${recipient}
EOF
  chmod 600 "$file"
}

assignment_hash() {
  awk '
    /^[[:space:]]*#/ { next }
    /^[[:space:]]*$/ { next }
    { sub(/\r$/, ""); print }
  ' "$1" | LC_ALL=C sort | sha256sum | awk '{print $1}'
}

cmd_init() {
  require_cmd age-keygen
  local key_dir
  key_dir="$(dirname "$SOPS_AGE_KEY_FILE")"
  mkdir -p "$key_dir"
  chmod 700 "$key_dir"
  if [[ -e "$SOPS_AGE_KEY_FILE" ]]; then
    echo "[secrets] age key already present: ${SOPS_AGE_KEY_FILE}"
  else
    if ! age-keygen -o "$SOPS_AGE_KEY_FILE" >/dev/null 2>&1; then
      rm -f "$SOPS_AGE_KEY_FILE"
      die "age-keygen failed"
    fi
    chmod 600 "$SOPS_AGE_KEY_FILE"
    echo "[secrets] wrote age key: ${SOPS_AGE_KEY_FILE}"
  fi
  local recipient
  recipient="$(age-keygen -y "$SOPS_AGE_KEY_FILE")"
  if [[ -f "$OPTIO_NEW_SOPS_CONFIG" && "${1:-}" != "--force" ]]; then
    local current
    current="$(first_line "$(sed -n 's/^[[:space:]]*age:[[:space:]]*//p' "$OPTIO_NEW_SOPS_CONFIG" | tr -d "\"'" || true)")"
    if [[ -n "$current" && "$current" != "$PLACEHOLDER_RECIPIENT" && "$current" != "$recipient" ]]; then
      die "secrets config already has a different recipient. Re-run with --force to replace it"
    fi
  fi
  write_sops_config "$recipient"
  echo "[secrets] recipient: ${recipient}"
  echo "[secrets] wrote ${OPTIO_NEW_SOPS_CONFIG}"
}

cmd_encrypt() {
  local force=0
  if [[ "${1:-}" == "--force" ]]; then
    force=1
    shift
  fi
  local plain="${1:-$PLAIN}"
  local cipher="${2:-$ENCRYPTED}"
  require_cmd sops
  [[ -f "$plain" ]] || die "missing plaintext env: ${plain}"
  [[ "$plain" != "$cipher" ]] || die "plaintext and ciphertext paths must differ"
  if [[ -e "$cipher" && "$force" != 1 ]]; then
    die "ciphertext exists: ${cipher} (re-run with --force)"
  fi
  local recipient
  recipient="$(read_recipient)"
  local tmp
  tmp="$(secret_tmp)"
  if ! sops --encrypt --age "$recipient" --input-type dotenv --output-type dotenv "$plain" >"$tmp"; then
    rm -f "$tmp"
    die "encrypt failed"
  fi
  chmod 600 "$tmp"
  mkdir -p "$(dirname "$cipher")"
  mv "$tmp" "$cipher"
  chmod 600 "$cipher"
  local count
  count="$(awk -F= '/^[A-Za-z_][A-Za-z0-9_]*=/{c++} END{print c+0}' "$plain")"
  echo "[secrets] encrypted ${count} keys -> ${cipher}"
}

cmd_check() {
  require_cmd sops
  [[ -f "$ENCRYPTED" ]] || die "missing ciphertext: ${ENCRYPTED}"
  [[ -f "$SOPS_AGE_KEY_FILE" ]] || die "missing age key: ${SOPS_AGE_KEY_FILE}"
  local tmp
  tmp="$(secret_tmp)"
  add_cleanup "$tmp"
  if ! sops --decrypt --input-type dotenv --output-type dotenv "$ENCRYPTED" >"$tmp"; then
    die "decrypt failed"
  fi
  chmod 600 "$tmp"
  local count
  count="$(awk -F= '/^[A-Za-z_][A-Za-z0-9_]*=/{c++} END{print c+0}' "$tmp")"
  [[ "$count" -gt 0 ]] || die "decrypted env has no assignments"
  if [[ -f "$PLAIN" ]]; then
    local left right
    left="$(assignment_hash "$PLAIN")"
    right="$(assignment_hash "$tmp")"
    [[ "$left" == "$right" ]] || die "decrypt-check hash mismatch (values not shown)"
    echo "[secrets] PASS check (${count} keys match plaintext)"
  else
    echo "[secrets] PASS check (${count} keys; plaintext file already absent)"
  fi
}

# Sets RESOLVED_ENV_FILE. Decrypts ciphertext to a 0600 tmpfs file and registers cleanup.
# Status text goes to stderr. The path is not a secret; the file contents are.
resolve_env_file() {
  RESOLVED_ENV_FILE=""
  local envfile=""
  if [[ -f "$ENCRYPTED" ]]; then
    require_cmd sops
    [[ -f "$SOPS_AGE_KEY_FILE" ]] || die "missing age key: ${SOPS_AGE_KEY_FILE}"
    envfile="$(secret_tmp)"
    add_cleanup "$envfile"
    if ! sops --decrypt --input-type dotenv --output-type dotenv "$ENCRYPTED" >"$envfile"; then
      die "decrypt failed"
    fi
    chmod 600 "$envfile"
  elif [[ -f "$PLAIN" ]]; then
    envfile="$PLAIN"
    echo "[secrets] using plaintext ${PLAIN}; run scripts/secrets.sh encrypt" >&2
  elif [[ -f "$ROOT/secrets/.env" ]]; then
    envfile="$ROOT/secrets/.env"
    echo "[secrets] using plaintext secrets/.env; run scripts/secrets.sh encrypt" >&2
  else
    die "no env file. Copy .env.example to .env, then run scripts/secrets.sh init && scripts/secrets.sh encrypt"
  fi
  RESOLVED_ENV_FILE="$envfile"
}

cmd_compose() {
  resolve_env_file
  require_cmd docker
  if [[ " $* " == *" up "* && -z "${COMPOSE_PROFILES:-}" && " $* " != *" --profile "* ]]; then
    echo "[secrets] COMPOSE_PROFILES is unset and no --profile was passed; kit-harness and orchestrator stay stopped (litellm still starts)" >&2
  fi
  docker compose --env-file "$RESOLVED_ENV_FILE" -f "$ROOT/docker-compose.yml" "$@"
}

cmd_run() {
  [[ $# -ge 1 ]] || die "usage: scripts/secrets.sh run <command> [args]"
  resolve_env_file
  set -a
  # shellcheck disable=SC1090
  . "$RESOLVED_ENV_FILE"
  set +a
  "$@"
}

audit_tracked_paths() {
  local bad=0
  while IFS= read -r -d '' f; do
    case "$f" in
      .env.example | secrets/.env.example | secrets/.sops.yaml.example) ;;
      .env | .env.* | secrets/.env | secrets/.sops.yaml | secrets/optio-new.env | secrets/age/* | *.agekey)
        echo "[secrets] FAIL tracked: ${f}" >&2
        bad=1
        ;;
    esac
  done < <(git ls-files -z)
  [[ "$bad" -eq 0 ]] || exit 1
}

audit_markers() {
  local age_marker openssh_marker rsa_marker
  age_marker="$(printf '%s%s' 'AGE-SECRET-KEY-' '1')"
  openssh_marker="$(printf '%s%s' 'BEGIN OPENSSH ' 'PRIVATE KEY')"
  rsa_marker="$(printf '%s%s' 'BEGIN RSA ' 'PRIVATE KEY')"
  local marker label
  for marker in "$age_marker" "$openssh_marker" "$rsa_marker"; do
    if git grep -I -l -F "$marker" -- . >/dev/null 2>&1; then
      echo "[secrets] FAIL secret marker in tracked files:" >&2
      git grep -I -l -F "$marker" -- .
      exit 1
    fi
  done
  label="$(printf '%s %s' 'set' '-x')"
  if grep -F -e "$label" "$ROOT/scripts/secrets.sh" >/dev/null 2>&1; then
    die "helper must not enable shell xtrace"
  fi
}

cmd_audit() {
  require_cmd git
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "not a git checkout"
  local path
  for path in .env secrets/.env secrets/.sops.yaml secrets/optio-new.env secrets/age/key.txt secrets/storagebox_ed25519; do
    git check-ignore -q -- "$path" || die "not gitignored: ${path}"
  done
  echo "[secrets] PASS gitignore"
  audit_tracked_paths
  echo "[secrets] PASS tracked paths"
  audit_markers
  echo "[secrets] PASS secret markers"
  echo "[secrets] PASS audit"
}

cmd_roundtrip() {
  if ! command -v sops >/dev/null 2>&1 || ! command -v age-keygen >/dev/null 2>&1; then
    if [[ "${SECRETS_ROUNDTRIP_REQUIRED:-0}" == "1" ]]; then
      die "sops and age-keygen are required"
    fi
    echo "[secrets] SKIP round-trip (sops or age-keygen missing)"
    return 0
  fi
  local work
  work="$(mktemp -d)"
  add_cleanup "$work"
  SOPS_AGE_KEY_FILE="$work/key.txt"
  OPTIO_NEW_SOPS_CONFIG="$work/.sops.yaml"
  PLAIN="$work/plain.env"
  ENCRYPTED="$work/cipher.env"
  export SOPS_AGE_KEY_FILE
  cmd_init
  cat >"$PLAIN" <<'EOF'
MODEL_API_KEY=
MODEL_ENDPOINT=http://127.0.0.1:4000/v1
OPTIO_NEW_POSTGRES_PASSWORD=changeme
LITELLM_MASTER_KEY=sk-change-me
EOF
  chmod 600 "$PLAIN"
  cmd_encrypt
  cmd_check
  echo "[secrets] PASS round-trip"
}

main() {
  local cmd="${1:-}"
  if [[ -z "$cmd" ]]; then
    usage
    exit 2
  fi
  shift
  case "$cmd" in
    init) cmd_init "$@" ;;
    encrypt) cmd_encrypt "$@" ;;
    check) cmd_check "$@" ;;
    compose) cmd_compose "$@" ;;
    run) cmd_run "$@" ;;
    audit) cmd_audit "$@" ;;
    roundtrip) cmd_roundtrip "$@" ;;
    -h | --help | help) usage ;;
    *)
      usage >&2
      die "unknown command: ${cmd}"
      ;;
  esac
}

main "$@"
