/**
 * Optio-New harness — TypeScript entry re-exports.
 * Language standard: TypeScript (Node 20+, ESM).
 */
export {
  cavemanRequested,
  createInstalledSkillLoader,
  DEFAULT_SKILL_BUDGET,
  runAgentLoop,
  type AgentLoopInput,
  type AgentLoopResult,
  type AgentToolRuntime,
  type AuditEvent,
  type AuditSink,
  type DecisionSidecar,
  type GateDecision,
  type GuardedToolResult,
  type LoadedSkill,
  type ModelAdapter,
  type ModelRequest,
  type ModelResponse,
  type ModelToolCall,
  type SidecarAdvice,
  type SkillBudget,
  type SkillLoader,
  type SkillResolveInput,
} from "./agent/loop.js";
export {
  createStubDecisionSidecar,
  DEFAULT_TOOL_TIMEOUT_MS,
  evaluateHardGates,
} from "./harness/gates/index.js";
export { createEnvModelAdapter, readModelEnv, type ModelEnvConfig } from "./agent/env-adapter.js";
export {
  IntakeHttpSchema,
  buildIntakeJob,
  createIntakeServer,
  handleIntakeRequest,
  IntakeTaskSchema,
  type IntakeAccepted,
  type IntakeHttpRequest,
  type IntakeServerOptions,
  type IntakeTask,
} from "./orchestrator/intake/index.js";
export {
  CANONICAL_SPAN,
  createStageTracer,
  getStageTracer,
  loadTelemetryExportConfig,
  resolveExporterTargets,
  type ActiveSpan,
  type ExporterTarget,
  type FinishedSpan,
  type SpanFields,
  type StageTracer,
  type TelemetryExportConfig,
} from "./orchestrator/telemetry/index.js";
export { processHelloWorld } from "./orchestrator/jobs/hello-world.js";
export {
  createPathWorkspacePort,
  createSessionGate,
  DEFAULT_SESSION_CONCURRENCY,
  InMemorySessionTelemetry,
  loadSessionConcurrencyConfig,
  readSessionFile,
  SessionConcurrencyConfigSchema,
  SessionGateError,
  SESSION_QUEUE_DEPTH_METRIC,
  SESSION_QUEUE_SPAN,
  workspacePortFromWorktreeManager,
  WorktreeAlreadyExistsError,
  writeSessionFile,
  type CodingProvider,
  type SessionAcquireRequest,
  type SessionAcquireResult,
  type SessionConcurrencyConfig,
  type SessionConcurrencySnapshot,
  type SessionGate,
  type SessionLease,
  type SessionQueueTicket,
  type SessionTelemetry,
  type SessionWorkspace,
  type SessionWorkspacePort,
  type WorktreeManagerLike,
} from "./orchestrator/sessions/index.js";
export {
  WorktreeIsolationError,
  WorktreeManager,
  createWorktreeStageHandler,
  worktreeKey,
  type CreateWorktreeOptions,
  type ReapResult,
  type WorktreeHandle,
  type WorktreeLifecycle,
  type WorktreeManagerOptions,
  type WorktreeReapOutcome,
} from "./orchestrator/worktrees/index.js";
export {
  PIPELINE_JOB_ATTEMPTS,
  PIPELINE_STAGES,
  STAGE_QUEUES,
  STAGE_STEPS,
  DEFAULT_REVIEW_GATE_ATTEMPTS,
  ReviewGateClosedError,
  StageNotReadyError,
  evaluateReviewGate,
  type ReviewGateBinding,
  type ReviewGateDecision,
  type ReviewGateEngine,
  type ReviewGateEvidence,
  type ReviewGatePath,
  type ReviewGateVerdict,
  InMemoryStepCursorStore,
  buildPipelineFlow,
  bullmqStageWorkerFactory,
  createAgentStageHandler,
  createPgStepCursorStore,
  createSqlStepCursorStore,
  enqueueIntakePipeline,
  loadPipelineStepCursorDdl,
  processStageJob,
  runPipeline,
  startStageGraph,
  type FlowEnqueuer,
  type PipelineRunResult,
  type PipelineStage,
  type SqlExecutor,
  type StageJobResult,
  type StageRuntime,
  type StageStepContext,
  type StageStepHandler,
  type StageLearningReader,
  type StageWorkerFactory,
  type StageWorkerHandle,
  type StepCursor,
  type StepCursorStore,
} from "./orchestrator/jobs/index.js";
export {
  LEARNING_QUEUE,
  InMemoryLearningStore,
  createDisabledMetaIssuePublisher,
  createGithubMetaIssuePublisher,
  createMetaIssuePublisherFromEnv,
  createPgLearningStore,
  createQueueLearningSink,
  createSqlLearningStore,
  failureFingerprint,
  formatPlannerLearnings,
  loadLearningsDdl,
  processLearningObservation,
  readLearningConfig,
  skillAdjustmentFromLearnings,
  startLearningWorker,
  type LearningJobResult,
  type LearningObservationInput,
  type LearningRecord,
  type LearningStore,
} from "./orchestrator/learning/index.js";
export type {
  CodingAgent,
  CodingAgentInput,
  CodingAgentOutput,
  CodingAgentStatus,
  CodingAgentUsage,
} from "./adapters/coding-agent.js";
export {
  buildCodexGatewayConfig,
  codexAdapter,
  codexOpenAiBaseUrl,
  createCodexAdapter,
} from "./adapters/codex/index.js";
export {
  CURSOR_NATIVE_API_ENDPOINT,
  createCursorAdapter,
  cursorAdapter,
} from "./adapters/cursor/index.js";
export {
  CodingBackendUndecidedError,
  createCodingAgent,
  resolveCodingBackend,
  type CodingAgentDeps,
  type CodingBackendId,
  type CodingBackendSelection,
} from "./adapters/select.js";
export {
  litellmOrigin,
  loadCavemanProxyConfig,
  resolveCodexUpstreamBaseUrl,
  type CavemanMode,
  type CavemanProxyConfig,
} from "./proxy/index.js";
export {
  checkCompletion,
  createKitHarnessServer,
  createModelRouter,
  decideTool,
  detectLoop,
  resolveListen,
  routeModel,
  splitOrProceed,
  type CompletionDecision,
  type CompletionEvidence,
  type DecisionAdvisor,
  type Hop1Choice,
  type LoopDetectResult,
  type RouteModelDecision,
  type SplitDecision,
  type ToolGateDecision,
} from "./kit-harness/index.js";
export {
  applyHop2Decision,
  createJevRouter,
  createLayaRouter,
  loadConfiguredHop2Router,
  loadHop2Router,
  resolveJevBaseUrl,
  resolveLayaBaseUrl,
  type CachedCompletion,
  type ExactPromptCache,
  type FetchLike,
  type Hop2PluginId,
  type Hop2Result,
  type JevRouter,
  type RoutingChoice,
  type RoutingDecision,
  type RoutingState,
} from "./gateway/jev-router/index.js";
