/**
 * Optio-New harness — TypeScript entry re-exports.
 * Language standard: TypeScript (Node 20+, ESM).
 */
export {
  cavemanRequested,
  createInstalledSkillLoader,
  DEFAULT_SKILL_BUDGET,
  runAgentLoop,
  type AgentLoopInput,
  type AgentLoopResult,
  type AgentToolRuntime,
  type AuditEvent,
  type AuditSink,
  type DecisionSidecar,
  type GateDecision,
  type GuardedToolResult,
  type LoadedSkill,
  type ModelAdapter,
  type ModelRequest,
  type ModelResponse,
  type ModelToolCall,
  type ModelUsage,
  type SidecarAdvice,
  type SkillBudget,
  type SkillLoader,
  type SkillResolveInput,
} from "./agent/loop.js";
export {
  createStubDecisionSidecar,
  DEFAULT_TOOL_TIMEOUT_MS,
  evaluateHardGates,
} from "./harness/gates/index.js";
export { createEnvModelAdapter, readModelEnv, type ModelEnvConfig } from "./agent/env-adapter.js";
export {
  BOT_INTAKE_CREATED,
  GITHUB_WEBHOOK_PATH,
  INTAKE_WEBHOOK_PATH,
  INTAKE_WEBHOOK_SIGNATURE_HEADER,
  IntakeHttpSchema,
  LINEAR_WEBHOOK_PATH,
  TRACKER_WEBHOOK_PATH,
  SLACK_WEBHOOK_PATH,
  buildIntakeJob,
  createIntakeServer,
  handleGithubWebhook,
  handleIntakeRequest,
  handleLinearWebhook,
  handleSlackWebhook,
  IntakeTaskSchema,
  signIntakeWebhookBody,
  signLinearBody,
  signSlackBody,
  type BotIntakeCreated,
  type IntakeAccepted,
  type IntakeHttpRequest,
  type IntakeServerOptions,
  type IntakeTask,
} from "./orchestrator/intake/index.js";
export {
  CANONICAL_SPAN,
  createStageTracer,
  getStageTracer,
  loadTelemetryExportConfig,
  resolveExporterTargets,
  type ActiveSpan,
  type ExporterTarget,
  type FinishedSpan,
  type SpanFields,
  type StageTracer,
  type TelemetryExportConfig,
} from "./orchestrator/telemetry/index.js";
export {
  REDACTED,
  SECRET_ENV_NAMES,
  formatAgentDump,
  formatStageLog,
  redactError,
  redactSecrets,
  redactValue,
} from "./security/redact.js";
export {
  HELLO_WORLD_RESPONSE,
  processHelloWorld,
  readPlanStage,
  runHelloWorldPlan,
  type HelloWorldPlanProof,
  type HelloWorldResponse,
  type PlanStageStatus,
  type PlanStageView,
} from "./orchestrator/jobs/hello-world.js";
export {
  createPathWorkspacePort,
  createSessionGate,
  DEFAULT_SESSION_CONCURRENCY,
  InMemorySessionTelemetry,
  loadSessionConcurrencyConfig,
  readSessionFile,
  SessionConcurrencyConfigSchema,
  SessionGateError,
  SESSION_QUEUE_DEPTH_METRIC,
  SESSION_QUEUE_SPAN,
  workspacePortFromWorktreeManager,
  WorktreeAlreadyExistsError,
  writeSessionFile,
  type CodingProvider,
  type SessionAcquireRequest,
  type SessionAcquireResult,
  type SessionConcurrencyConfig,
  type SessionConcurrencySnapshot,
  type SessionGate,
  type SessionLease,
  type SessionQueueTicket,
  type SessionTelemetry,
  type SessionWorkspace,
  type SessionWorkspacePort,
  type WorktreeManagerLike,
} from "./orchestrator/sessions/index.js";
export {
  SkillBudgetDeniedError,
  createWorkflowSkillLoader,
  type ComputeAllowListInput,
  type WorkflowLoadedSkill,
  type WorkflowSkillLoader,
  type WorkflowSkillLoaderOptions,
} from "./orchestrator/skills/index.js";
export {
  createEveHttpServer,
  EveRequestError,
  EveStepInputSchema,
  executeCli,
  runEveStep,
  startEveHttpServer,
  type EveStepInput,
  type EveStepResult,
} from "./eve/index.js";
export { runEveStageStep } from "./orchestrator/jobs/stage-worker.js";
export {
  WorktreeIsolationError,
  WorktreeManager,
  createSkillStageHook,
  createWorktreeManagerFromEnv,
  createWorktreeStageHandler,
  loadWorktreeRuntimeConfig,
  worktreeKey,
  type CreateWorktreeOptions,
  type ReapResult,
  type WorktreeHandle,
  type WorktreeLifecycle,
  type WorktreeManagerOptions,
  type WorktreeReapOutcome,
  type WorktreeRuntimeConfig,
  type WorktreeSkillStageHook,
} from "./orchestrator/worktrees/index.js";
export {
  DEFAULT_REPO_ID,
  RepoCatalogError,
  RepoWorktreeRouter,
  UnknownRepoError,
  createGuardedRepoWorktrees,
  loadRepoCatalog,
  matchRepoId,
  readWorkflowRepoId,
  resolveRepo,
  selectRepoId,
  type RepoBinding,
  type RepoCatalog,
} from "./orchestrator/repos/index.js";
export {
  DEFAULT_RESOURCE_THRESHOLDS,
  InMemoryTaskStatusStore,
  ResourceGuard,
  ResourceGuardError,
  createHostResourceProbe,
  loadResourceThresholds,
  type ResourceProbe,
  type ResourceThresholds,
  type TaskStatusRecord,
} from "./orchestrator/resources/index.js";
export {
  EveRunnerStepSchema,
  IMPLEMENTATION_AGENT_ID,
  IMPLEMENTATION_PARENT_TOOLS,
  IMPLEMENTATION_STEP_ID,
  SPECIALIST_ADVANCE_INPUT_KEYS,
  SPECIALIST_IDS,
  STEP_ADVANCE_TOOLS,
  SpecialistInvokeError,
  dispatchSpecialistTool,
  implementationSpecialistsAllowed,
  invokeSpecialist,
  isSpecialistId,
  isStepAdvanceTool,
  loadSpecialistCatalog,
  specialistSkillBudget,
  specialistToolBudget,
  type EveRunnerStep,
  type SpecialistCatalog,
  type SpecialistExecutor,
  type SpecialistId,
  type SpecialistInvokeOptions,
  type SpecialistInvokeResult,
  type SpecialistRecord,
  type SpecialistRunRequest,
} from "./orchestrator/specialists/index.js";
export {
  PIPELINE_JOB_ATTEMPTS,
  PIPELINE_STAGES,
  STAGE_QUEUES,
  STAGE_STEPS,
  DEFAULT_REVIEW_GATE_ATTEMPTS,
  ReviewGateClosedError,
  PrSafetyClosedError,
  StageNotReadyError,
  collectPrSafetyInput,
  evaluatePrSafetyGate,
  evaluateReviewGate,
  type PrSafetyDecision,
  type PrSafetyFinding,
  type PrSafetyInput,
  type ShellRunner,
  type ReviewGateBinding,
  type ReviewGateDecision,
  type ReviewGateEngine,
  type ReviewGateEvidence,
  type ReviewGatePath,
  type ReviewGateVerdict,
  InMemoryStepCursorStore,
  buildPipelineFlow,
  ApprovalRejectedError,
  ApprovalReplanError,
  ApprovalRequiredError,
  BudgetExceededError,
  DEFAULT_HITL_CONFIDENCE_THRESHOLD,
  DEFAULT_TASK_MAX_TOKENS,
  DEFAULT_TASK_MAX_USD,
  HitlDecisionError,
  InMemoryHitlStore,
  InMemoryUsageStore,
  applyHitlDecision,
  approveMergeForReviewAgent,
  bullmqStageWorkerFactory,
  createAgentStageHandler,
  createHitlQueuePort,
  createSqlUsageStore,
  StageCredentialsError,
  JsonFileStepCursorStore,
  createProductionStageHandler,
  createPgStepCursorStore,
  createSqlStepCursorStore,
  CiPendingError,
  delayJobForApproval,
  enqueueIntakePipeline,
  evaluateHitlGate,
  loadHitlApprovalDdl,
  loadHitlConfig,
  loadPipelineStepCursorDdl,
  loadTaskBudgetCaps,
  loadTaskUsageDdl,
  openOrchestratorDatabase,
  processStageJob,
  readStageCheckpoint,
  readTaskBudgetStatus,
  runPipeline,
  startStageGraph,
  type BudgetBinding,
  type FlowEnqueuer,
  type HitlAction,
  type HitlBinding,
  type HitlConfig,
  type HitlJobQueue,
  type HitlPoint,
  type HitlQueuePort,
  type HitlRecord,
  type PipelineRunResult,
  type PipelineStage,
  type SqlExecutor,
  type OrchestratorDatabase,
  type StageCheckpoint,
  type StageJobResult,
  type StageRuntime,
  type StageStepContext,
  type StageStepHandler,
  type HitlNotifyEvent,
  type StageStepResult,
  type StageStepUsage,
  type TaskBudgetCaps,
  type TaskBudgetStatus,
  type ProductionWorktrees,
  type StageLearningReader,
  type StageWorkerFactory,
  type StageWorkerHandle,
  type StepCursor,
  type StepCursorStore,
} from "./orchestrator/jobs/index.js";
export {
  InMemoryStageRunStore,
  createPgStageRunStore,
  createSqlStageRunStore,
  createStageRunLog,
  loadPipelineStageRunDdl,
  type AgentActionEntry,
  type StageRunLog,
  type StageRunRecord,
  type StageRunView,
  type StageUsageEntry,
  type StageUsageReport,
  type TaskRunView,
} from "./orchestrator/observability/index.js";
export {
  DEFAULT_ARTIFACT_LIMITS,
  InMemorySessionArtifactStore,
  buildSessionArtifact,
  createSqlSessionArtifactStore,
  dumpSessionArtifactTrail,
  executeDumpCli,
  loadSessionArtifactsDdl,
  readArtifactLimits,
  type ArtifactLimits,
  type ArtifactSql,
  type SessionArtifact,
  type SessionArtifactStore,
  type SessionArtifactTrail,
} from "./orchestrator/artifacts/index.js";
export {
  LEARNING_QUEUE,
  InMemoryLearningStore,
  createDisabledMetaIssuePublisher,
  createGithubMetaIssuePublisher,
  createMetaIssuePublisherFromEnv,
  githubMetaIssuesEnabled,
  createPgLearningStore,
  createQueueLearningSink,
  createSqlLearningStore,
  failureFingerprint,
  formatPlannerLearnings,
  loadLearningsDdl,
  processLearningObservation,
  readLearningConfig,
  skillAdjustmentFromLearnings,
  startLearningWorker,
  type LearningJobResult,
  type LearningObservationInput,
  type LearningRecord,
  type LearningStore,
} from "./orchestrator/learning/index.js";
export type {
  CodingAgent,
  CodingAgentInput,
  CodingAgentOutput,
  CodingAgentStatus,
  CodingAgentUsage,
} from "./adapters/coding-agent.js";
export {
  PERMISSION_TIERS,
  WORKFLOW_STAGE_PERMISSION,
  authorizeAgentRun,
  authorizeToolAction,
  defaultPermissionForStep,
  type PermissionTier,
} from "./kit-harness/permissions.js";
export {
  buildCodexGatewayConfig,
  codexAdapter,
  codexOpenAiBaseUrl,
  createCodexAdapter,
} from "./adapters/codex/index.js";
export {
  CURSOR_NATIVE_API_ENDPOINT,
  createCursorAdapter,
  cursorAdapter,
} from "./adapters/cursor/index.js";
export { createFlueAdapter, flueAdapter, type FlueAdapterDeps } from "./adapters/flue/index.js";
export {
  DEFAULT_FLUE_BASE_URL,
  DEFAULT_FLUE_MAX_ATTEMPTS,
  DEFAULT_FLUE_TIMEOUT_MS,
  FlueHttpError,
  createFlueClient,
  resolveFlueBaseUrl,
  type FlueClient,
  type FlueClientOptions,
  type FlueFetch,
} from "./adapters/flue/client.js";
export {
  FlueDispatchRequestSchema,
  FlueDispatchResponseSchema,
  FlueHealthResponseSchema,
  FlueSandboxModeSchema,
  FlueStartRequestSchema,
  FlueStartResponseSchema,
  FlueUsageEventSchema,
  type FlueDispatchRequest,
  type FlueDispatchResponse,
  type FlueHealthResponse,
  type FlueSandboxMode,
  type FlueStartRequest,
  type FlueStartResponse,
  type FlueUsageEvent,
} from "./adapters/flue/contract.js";
export {
  FLUE_FEEDBACK_MAX_ITEMS,
  FLUE_IMPLEMENT_BINDING_STAGE,
  InMemoryFlueSessionBindingStore,
  capFeedback,
  flueBindingKey,
  getDefaultFlueSessionBindingStore,
  resetDefaultFlueSessionBindingStore,
  type FlueBindingStage,
  type FlueReviewFeedbackItem,
  type FlueSessionBinding,
  type FlueSessionBindingPut,
  type FlueSessionBindingStore,
} from "./adapters/flue/session-binding.js";
export {
  FlueReviewFeedbackSchema,
  appendReviewFeedback,
  clearReviewFeedback,
  formatAccumulatedFeedback,
  type FlueReviewFeedback,
} from "./adapters/flue/review-feedback.js";
export {
  createPassthroughJevSkillPick,
  formatSkillPickInstructions,
  type JevSkillPickInput,
  type JevSkillPickPort,
  type JevSkillPickResult,
} from "./adapters/flue/jev-lazy-load.js";
export {
  CURSOR_IMPLEMENT_ACI_POLICY,
  DEFAULT_SEARCH_SUMMARY_LIMIT,
  EMPTY_COMMAND_OBSERVATION,
  MAX_SEARCH_SUMMARY_LIMIT,
  checkSyntax,
  cursorImplementPrompt,
  formatCommandObservation,
  gateFileEdit,
  isCursorImplementStep,
  summarizeSearch,
  type EditGateResult,
  type FileEdit,
  type LintDiagnostic,
  type SyntaxChecker,
} from "./adapters/cursor/implement-feedback.js";
export {
  CodingBackendUndecidedError,
  applyBackendCascade,
  createCodingAgent,
  resolveCodingBackend,
  resolveCodingBackendWithCascade,
  type CascadeCodingDecision,
  type CodingAgentDeps,
  type CodingBackendId,
  type CodingBackendSelection,
} from "./adapters/select.js";
export {
  litellmOrigin,
  loadCavemanProxyConfig,
  resolveCodexUpstreamBaseUrl,
  type CavemanMode,
  type CavemanProxyConfig,
} from "./proxy/index.js";
export {
  checkCompletion,
  createKitHarnessServer,
  createModelRouter,
  decideTool,
  detectLoop,
  resolveListen,
  routeModel,
  splitOrProceed,
  type CompletionDecision,
  type CompletionEvidence,
  type DecisionAdvisor,
  type Hop1Choice,
  type LoopDetectResult,
  type RouteModelDecision,
  type SplitDecision,
  type ToolGateDecision,
} from "./kit-harness/index.js";
export {
  BACKEND_CASCADE_QUESTION,
  BackendCascadeAnswerSchema,
  BackendCascadeConfigSchema,
  BackendCascadeLabelSchema,
  BackendCascadeStateSchema,
  BackendCascadeTimeoutError,
  DEFAULT_CASCADE_MIN_CONFIDENCE,
  DEFAULT_CASCADE_TIMEOUT_MS,
  DEFAULT_JEV_TIMEOUT_MS,
  DEFAULT_PLAN_MIN_CONFIDENCE,
  DEFAULT_PLAN_TIMEOUT_MS,
  JEV_GATE_SEQUENCE,
  JevGateKindSchema,
  PINNED_JEV_MODEL,
  PLAN_GATE_QUESTION,
  PlanGateAnswerSchema,
  PlanGateConfigSchema,
  PlanGateLabelSchema,
  PlanGateStateSchema,
  PlanGateTimeoutError,
  applyHop2Decision,
  createJevClient,
  createJevRouter,
  createLayaRouter,
  loadConfiguredHop2Router,
  loadHop2Router,
  mapCascadeLabelToTarget,
  resolveJevBaseUrl,
  resolveLayaBaseUrl,
  runBackendCascadeGate,
  runPlanGate,
  runJevDecide,
  runJevEvaluate,
  createJevMcpServer,
  startJevMcpStdio,
  noopJevMcpTelemetry,
  ContentLengthParser,
  encodeContentLengthMessage,
  JEV_MCP_TOOLS,
  JevMidrunInputSchema,
  MAX_MCP_CONTENT_LENGTH,
  type BackendCascadeAnswer,
  type BackendCascadeConfig,
  type BackendCascadeLabel,
  type BackendCascadeOutcome,
  type BackendCascadeState,
  type CachedCompletion,
  type CascadeCodingTarget,
  type CascadeModelTier,
  type ExactPromptCache,
  type FetchLike,
  type Hop2PluginId,
  type Hop2Result,
  type JevClient,
  type JevClientResult,
  type JevFetchLike,
  type JevGateKind,
  type JevDecideOutcome,
  type JevEvaluateOutcome,
  type JevMcpDecisionEvent,
  type JevMcpServer,
  type JevMcpTelemetry,
  type JevMidrunInput,
  type JevRouter,
  type PlanGateAnswer,
  type PlanGateConfig,
  type PlanGateLabel,
  type PlanGateOutcome,
  type PlanGateState,
  type RoutingChoice,
  type RoutingDecision,
  type RoutingState,
} from "./gateway/jev-router/index.js";
export { createOtelJevMcpTelemetry } from "./jev-mcp/otel-telemetry.js";
export {
  applyPlanGate,
  evaluatePlanWithGate,
  type PlanGateAction,
  type PlanGateDecision,
  type PlanGateLogEntry,
  type PlanGateLogFn,
} from "./orchestrator/jev/index.js";
export {
  loadEvalFixtures,
  renderEvalReport,
  runHarnessEval,
  writeEvalReport,
  type EvalCaseReport,
  type EvalFixture,
  type EvalReport,
} from "./eval/harness-eval.js";
